config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get '/signup', to: 'users#new'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help; end

  def about; end

  def contact; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>StaticPages#<%= yield(:title).downcase %></h1>
<p>
  To go to 'home' press: <a href="/static_pages/home">this</a>.
  <br>
  To go to 'help' press: <a href="/static_pages/help">this</a>.
  <br>
  To go to 'contact' press: <a href="/static_pages/contact">this</a>.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>StaticPages#<%= yield(:title).downcase %></h1>
<p>
  To go to 'home' press: <a href="/static_pages/home">this</a>.
  <br>
  To go to 'help' press: <a href="/static_pages/help">this</a>.
  <br>
  To go to 'about' press: <a href="/static_pages/about">this</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>StaticPages#<%= yield(:title).downcase %></h1>
<p>
  To go to 'home' press: <a href="/static_pages/home">this</a>.
  <br>
  To go to 'contact' press: <a href="/static_pages/contact">this</a>.
  <br>
  To go to 'about' press: <a href="/static_pages/about">this</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails logo"),
              'http://rubyonrails.org/' %>
<% end %>